#!/usr/bin/env node
/**
 * PrismAI Plugin Scaffold Tool
 *
 * Creates a new PrismAI plugin directory with a manifest and handler stub.
 *
 * Usage:
 *   node server/utils/plugins/scaffold.js <plugin-id> [display-name] [tool1] [tool2] ...
 *
 * Arguments:
 *   plugin-id      Required. Must match /^[a-z0-9][a-z0-9_-]*$/ and be 1-64 chars.
 *                  Becomes the directory name and manifest id.
 *   display-name   Optional. Human-readable name. Defaults to title-cased plugin-id.
 *   tool1 tool2    Optional. Tool names (each must match /^[a-zA-Z][a-zA-Z0-9_]*$/).
 *                  Defaults to a single tool named after the plugin-id (hyphens -> underscores).
 *
 * Exit codes:
 *   0  Success — files created.
 *   1  Validation error (bad name, directory exists, bad tool name, duplicates).
 *   2  I/O error (cannot create directory or write files).
 */

"use strict";

const fs = require("fs");
const path = require("path");

// ── Regex patterns (same as manifest-validator.js) ──────────────────────────
const PLUGIN_ID_RE = /^[a-z0-9][a-z0-9_-]*$/;
const TOOL_KEY_RE = /^[a-zA-Z][a-zA-Z0-9_]*$/;

// ── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Resolve the prismai-plugins directory.
 * Mirrors the registry's path logic so scaffold creates plugins where the
 * registry will find them.
 *
 * @returns {string} Absolute path to the prismai-plugins directory.
 */
function resolvePluginsDir() {
  if (process.env.STORAGE_DIR) {
    return path.resolve(process.env.STORAGE_DIR, "plugins", "prismai-plugins");
  }
  // __dirname is server/utils/plugins — go up two levels to server/, then down.
  return path.resolve(__dirname, "../../storage/plugins/prismai-plugins");
}

/**
 * Convert a kebab-case or snake_case string to Title Case.
 * Examples: "my-plugin" -> "My Plugin", "my_plugin" -> "My Plugin"
 *
 * @param {string} str
 * @returns {string}
 */
function toTitleCase(str) {
  return str
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

/**
 * Convert a plugin-id to a default tool name.
 * Hyphens are replaced with underscores; result must satisfy TOOL_KEY_RE.
 *
 * @param {string} pluginId
 * @returns {string}
 */
function defaultToolName(pluginId) {
  return pluginId.replace(/-/g, "_");
}

/**
 * Generate the content for plugin.prismai.json.
 *
 * @param {string} pluginId
 * @param {string} displayName
 * @param {string[]} tools
 * @returns {string}
 */
function generateManifest(pluginId, displayName, tools) {
  const toolDefs = {};
  for (const tool of tools) {
    toolDefs[tool] = {
      description: "TODO: Describe what " + tool + " does",
      parameters: {
        type: "object",
        properties: {},
        required: [],
      },
    };
  }

  const manifest = {
    id: pluginId,
    name: displayName,
    version: "0.1.0",
    schemaVersion: "1.0.0",
    author: "",
    license: "MIT",
    description: "TODO: Add plugin description",
    runtime: {
      entrypoint: "handler.js",
      timeout: 30000,
    },
    tools: toolDefs,
  };

  return JSON.stringify(manifest, null, 2) + "\n";
}

/**
 * Generate the content for handler.js.
 *
 * @param {string} displayName
 * @param {string[]} tools
 * @returns {string}
 */
function generateHandler(displayName, tools) {
  const lines = [];

  lines.push("/**");
  lines.push(" * " + displayName + " handler");
  lines.push(" * Generated by PrismAI plugin scaffold tool.");
  lines.push(" */");
  lines.push("");

  for (const tool of tools) {
    lines.push("/**");
    lines.push(" * @param {object} args");
    lines.push(" * @returns {object}");
    lines.push(" */");
    lines.push("function " + tool + "(args) {"); // eslint-disable-line no-unused-vars
    lines.push('  // TODO: Implement ' + tool);
    lines.push('  return { message: "' + tool + ' not yet implemented" };');
    lines.push("}");
    lines.push("");
  }

  lines.push("module.exports = { " + tools.join(", ") + " };");
  lines.push("");

  return lines.join("\n");
}

/**
 * Print usage information to stderr and exit with code 1.
 */
function printUsageAndExit() {
  process.stderr.write(
    [
      "Usage: node server/utils/plugins/scaffold.js <plugin-id> [display-name] [tool1] [tool2] ...",
      "",
      "Arguments:",
      "  plugin-id      Required. Must match /^[a-z0-9][a-z0-9_-]*$/ and be 1-64 chars.",
      "  display-name   Optional. Human-readable name (quote if it contains spaces).",
      "                 Defaults to title-cased plugin-id.",
      "  tool1 tool2    Optional. Tool names (each must match /^[a-zA-Z][a-zA-Z0-9_]*$/).",
      "                 Defaults to a single tool named after the plugin-id.",
      "",
      "Examples:",
      "  node server/utils/plugins/scaffold.js my-plugin",
      '  node server/utils/plugins/scaffold.js my-plugin "My Plugin" tool_one tool_two',
      "",
    ].join("\n")
  );
  process.exit(1);
}

// ── Main ─────────────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);

  // 1. Require at least one argument (plugin-id)
  if (args.length === 0) {
    printUsageAndExit();
  }

  const pluginId = args[0];

  // 2. Validate plugin-id format
  if (!PLUGIN_ID_RE.test(pluginId)) {
    process.stderr.write(
      'Error: plugin-id "' +
        pluginId +
        '" is invalid. Must match /^[a-z0-9][a-z0-9_-]*$/\n'
    );
    process.exit(1);
  }

  // 3. Validate plugin-id length
  if (pluginId.length > 64) {
    process.stderr.write(
      'Error: plugin-id "' +
        pluginId +
        '" is too long (' +
        pluginId.length +
        " chars). Maximum is 64 characters.\n"
    );
    process.exit(1);
  }

  // 4. Determine display-name and tool names from remaining args.
  //    If args[1] does NOT look like a tool name (i.e., it contains spaces or
  //    fails TOOL_KEY_RE), treat it as the display-name.
  let displayName;
  let toolArgs;

  if (args.length >= 2) {
    const candidate = args[1];
    // If candidate doesn't match TOOL_KEY_RE, it's a display-name
    if (!TOOL_KEY_RE.test(candidate)) {
      displayName = candidate;
      toolArgs = args.slice(2);
    } else {
      // It's a tool name — display-name defaults
      displayName = null;
      toolArgs = args.slice(1);
    }
  } else {
    displayName = null;
    toolArgs = [];
  }

  // 5. Resolve display-name default
  if (!displayName || displayName.trim() === "") {
    displayName = toTitleCase(pluginId);
  }

  // 6. Resolve tool names
  let tools;
  if (toolArgs.length === 0) {
    tools = [defaultToolName(pluginId)];
  } else {
    tools = toolArgs;
  }

  // 7. Validate each tool name
  for (const tool of tools) {
    if (!TOOL_KEY_RE.test(tool)) {
      process.stderr.write(
        'Error: tool name "' +
          tool +
          '" is invalid. Must match /^[a-zA-Z][a-zA-Z0-9_]*$/\n'
      );
      process.exit(1);
    }
  }

  // 8. Check for duplicate tool names
  const toolSet = new Set(tools);
  if (toolSet.size !== tools.length) {
    const seen = new Set();
    const dupes = [];
    for (const t of tools) {
      if (seen.has(t)) dupes.push(t);
      seen.add(t);
    }
    process.stderr.write(
      "Error: duplicate tool names: " + dupes.join(", ") + "\n"
    );
    process.exit(1);
  }

  // 9. Resolve output directory
  const pluginsDir = resolvePluginsDir();
  const pluginDir = path.join(pluginsDir, pluginId);

  // 10. Refuse to overwrite existing directory
  if (fs.existsSync(pluginDir)) {
    process.stderr.write(
      "Error: Plugin directory already exists: " + pluginDir + "\n"
    );
    process.exit(1);
  }

  // 11. Check plugins directory is writable (or createable)
  try {
    fs.mkdirSync(pluginDir, { recursive: true });
  } catch (mkdirErr) {
    process.stderr.write(
      "Error: Could not create plugin directory " +
        pluginDir +
        ": " +
        mkdirErr.message +
        "\n"
    );
    process.exit(2);
  }

  // 12. Write plugin.prismai.json
  const manifestPath = path.join(pluginDir, "plugin.prismai.json");
  try {
    fs.writeFileSync(manifestPath, generateManifest(pluginId, displayName, tools), "utf8");
  } catch (writeErr) {
    process.stderr.write(
      "Error: Could not write " + manifestPath + ": " + writeErr.message + "\n"
    );
    process.exit(2);
  }

  // 13. Write handler.js
  const handlerPath = path.join(pluginDir, "handler.js");
  try {
    fs.writeFileSync(handlerPath, generateHandler(displayName, tools), "utf8");
  } catch (writeErr) {
    process.stderr.write(
      "Error: Could not write " + handlerPath + ": " + writeErr.message + "\n"
    );
    process.exit(2);
  }

  // 14. Report success
  // Compute a display-friendly relative path from likely CWD
  const relDir =
    "storage/plugins/prismai-plugins/" + pluginId + "/";

  const filesCreated = ["plugin.prismai.json", "handler.js"];

  process.stdout.write(
    [
      'Created PrismAI plugin "' + pluginId + '" at:',
      "  " + relDir,
      "",
      "Files:",
      filesCreated.map((f) => "  " + f).join("\n"),
      "",
      "Next steps:",
      "  1. Edit plugin.prismai.json to add tool descriptions and parameters",
      "  2. Implement tool functions in handler.js",
      "  3. Add a health.js if your plugin depends on external services",
      "  4. Test: node -e \"const {PrismAIPluginRegistry} = require('./server/utils/plugins/registry'); PrismAIPluginRegistry.discoverAndValidate().then(r => console.log(r))\"",
      "",
    ].join("\n")
  );

  process.exit(0);
}

main();
